#!/usr/bin/env python3
"""Generate app/evals/holdout_150_prompts.json — unseen Phase 1.2 holdout suite."""

from __future__ import annotations

import json
from pathlib import Path

SERVICE_ROOT = Path(__file__).resolve().parent.parent
OUT = SERVICE_ROOT / "app" / "evals" / "holdout_150_prompts.json"

# (category_key, category_label, expected_intent, prompt)
CASES: list[tuple[str, str, str, str]] = [
    # A. Direct town lookup and factual questions
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "How far is Gardner from Boston according to your data?"),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "What commute data do you have for Shrewsbury?"),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "Tell me Burlington's stored home price and commute."),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "What is Acton's crime rate and safety score?"),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "Is Sharon considered a full-data town or partial-data town?"),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "What information is missing for Worcester?"),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "Give me the basic stats for Westborough."),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "What is Westford's school score?"),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "Does your dataset have a housing price for Grafton?"),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "What is the Boston commute for Rockport?"),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "How expensive is Needham in your data?"),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "What is the safety score for Chelsea?"),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "Tell me the commute, price, and school score for Waltham."),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "Is Upton missing any important fields?"),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "What county and region is Salem in?"),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "Does Newton have school data in your dataset?"),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "What is the drive distance from Milton to Boston?"),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "Give me a data-quality summary for Freetown."),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "What is the affordability score for Lynn?"),
    ("A_lookup", "A. Direct town lookup and factual questions", "lookup_single_town",
     "Is Manchester-by-the-Sea marked coastal?"),
    # B. Dataset membership, unknown towns, and aliases
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "lookup_single_town",
     "Do you cover Westboro?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "lookup_single_town",
     "Is Westborough included?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "lookup_single_town",
     "Is Charlton part of your suburb list?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "lookup_single_town",
     "Do you have data for Marlboro or Marlborough?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "lookup_single_town",
     "Is Manchester by the Sea the same as Manchester-by-the-Sea in your data?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "refuse_out_of_scope",
     "Do you include Brooklyn, MA?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "lookup_single_town",
     "Is Brookline in the dataset?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "lookup_single_town",
     "Do you have Dover?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "lookup_single_town",
     "Is Foxboro included, or only Foxborough?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "lookup_single_town",
     "Do you have Northboro in the list?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "lookup_single_town",
     "Is Northborough covered?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "lookup_single_town",
     "Is Stoughton in your data?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "refuse_out_of_scope",
     "Do you include Providence?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "refuse_out_of_scope",
     "Do you cover Nashua?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "lookup_single_town",
     "Is Lowell included?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "refuse_out_of_scope",
     "Is Amherst part of this Boston-suburb dataset?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "refuse_out_of_scope",
     "Do you have Springfield?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "refuse_out_of_scope",
     "Can you recommend Charlton if it is not in your dataset?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "lookup_single_town",
     "What towns are closest matches to \"Worester\"?"),
    ("B_membership", "B. Dataset membership, unknown towns, and aliases", "lookup_single_town",
     "Is \"Manchester\" ambiguous in your town list?"),
    # C. Typo and fuzzy town normalization
    ("C_typo", "C. Typo and fuzzy town normalization", "lookup_single_town",
     "What's the commute from Shreusbury?"),
    ("C_typo", "C. Typo and fuzzy town normalization", "lookup_single_town",
     "Tell me about Woster."),
    ("C_typo", "C. Typo and fuzzy town normalization", "compare_towns",
     "Compare Lexingtn and Concord."),
    ("C_typo", "C. Typo and fuzzy town normalization", "lookup_single_town",
     "Is Westborugh in the list?"),
    ("C_typo", "C. Typo and fuzzy town normalization", "lookup_single_town",
     "How safe is Brlington?"),
    ("C_typo", "C. Typo and fuzzy town normalization", "lookup_single_town",
     "Give me home price for Framinghm."),
    ("C_typo", "C. Typo and fuzzy town normalization", "compare_towns",
     "Compare Marlboro and Shrewsbury."),
    ("C_typo", "C. Typo and fuzzy town normalization", "lookup_single_town",
     "Commute from Neddham to Boston?"),
    ("C_typo", "C. Typo and fuzzy town normalization", "lookup_single_town",
     "Is Manchster-by-the-Sea coastal?"),
    ("C_typo", "C. Typo and fuzzy town normalization", "compare_towns",
     "Compare Newbury Port and Ipswich."),
    ("C_typo", "C. Typo and fuzzy town normalization", "lookup_single_town",
     "What is the crime rate for Chelsa?"),
    ("C_typo", "C. Typo and fuzzy town normalization", "compare_towns",
     "Is Waylnd safer than Weston?"),
    ("C_typo", "C. Typo and fuzzy town normalization", "compare_towns",
     "Compare Wellesly and Newton."),
    ("C_typo", "C. Typo and fuzzy town normalization", "lookup_single_town",
     "Tell me about North Readng."),
    ("C_typo", "C. Typo and fuzzy town normalization", "lookup_single_town",
     "Is Swampscot coastal?"),
    # D. Comparison and relative-property questions
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Which is safer, Acton or Framingham?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Which is cheaper, Burlington or Waltham?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Which has better schools, Sharon or Westford?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Which has a shorter commute, Brookline or Newton?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Which is more affordable, Lexington or Winchester?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Is Shrewsbury safer than Worcester?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Is Marblehead more expensive than Swampscott?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Does Salem or Beverly have lower crime?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Which is better for schools, Needham or Wellesley?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Which is better for affordability, Lynn or Revere?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Compare Quincy and Braintree for commute and safety."),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Compare Westborough and Grafton for schools."),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Which is more family-friendly, Acton or Concord?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Which is a better value, Reading or North Reading?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Which has worse safety, Chelsea or Lynn?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Is Newton significantly more expensive than Waltham?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Is Burlington safer than Waltham?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Compare Cambridge and Brookline for price and school score."),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Which is better if I care about schools but not price, Weston or Sharon?"),
    ("D_compare", "D. Comparison and relative-property questions", "compare_towns",
     "Which has the stronger overall profile, Medfield or Scituate?"),
    # E. Budget constraints and affordability
    ("E_budget", "E. Budget constraints and affordability", "recommend_structured",
     "Find me towns under 700k with decent schools and safety."),
    ("E_budget", "E. Budget constraints and affordability", "recommend_structured",
     "Give me good options under 650k, but don't include missing-price towns."),
    ("E_budget", "E. Budget constraints and affordability", "recommend_structured",
     "What are the strongest towns under 800k if commute matters?"),
    ("E_budget", "E. Budget constraints and affordability", "recommend_structured",
     "Find towns below 900k with above-average school scores."),
    ("E_budget", "E. Budget constraints and affordability", "recommend_structured",
     "I have a 600k budget and care most about safety."),
    ("E_budget", "E. Budget constraints and affordability", "recommend_structured",
     "I have 1 million dollars max. What are the best family towns?"),
    ("E_budget", "E. Budget constraints and affordability", "recommend_structured",
     "My max is $1.1m; prioritize schools and safety."),
    ("E_budget", "E. Budget constraints and affordability", "recommend_structured",
     "Find options under 750,000 with a reasonable commute."),
    ("E_budget", "E. Budget constraints and affordability", "recommend_structured",
     "Give me cheaper towns under 550k, but warn me about tradeoffs."),
    ("E_budget", "E. Budget constraints and affordability", "recommend_structured",
     "What can I realistically get below 500k?"),
    ("E_budget", "E. Budget constraints and affordability", "recommend_structured",
     "Find towns under 400k, but be honest if there are no matches."),
    ("E_budget", "E. Budget constraints and affordability", "recommend_structured",
     "Find towns around 900k or less, ideally coastal."),
    ("E_budget", "E. Budget constraints and affordability", "recommend_structured",
     "Exclude anything over 850k."),
    ("E_budget", "E. Budget constraints and affordability", "recommend_structured",
     "Find me towns under $1m that are not partial data."),
    ("E_budget", "E. Budget constraints and affordability", "recommend_structured",
     "Find the best full-data towns below $700k."),
    # F. Commute constraints and distance logic
    ("F_commute", "F. Commute constraints and distance logic", "recommend_structured",
     "Show me towns within 25 minutes of Boston."),
    ("F_commute", "F. Commute constraints and distance logic", "recommend_structured",
     "Find towns under 35 minutes with good schools."),
    ("F_commute", "F. Commute constraints and distance logic", "recommend_structured",
     "I want a commute between 35 and 50 minutes."),
    ("F_commute", "F. Commute constraints and distance logic", "recommend_structured",
     "Give me family towns farther than 45 minutes from Boston."),
    ("F_commute", "F. Commute constraints and distance logic", "recommend_structured",
     "Find good towns at least 50 minutes away."),
    ("F_commute", "F. Commute constraints and distance logic", "recommend_structured",
     "I want a long commute but better affordability."),
    ("F_commute", "F. Commute constraints and distance logic", "recommend_structured",
     "Find towns close to Boston but safer than average."),
    ("F_commute", "F. Commute constraints and distance logic", "recommend_structured",
     "Find towns not too close to Boston, maybe 40+ minutes out."),
    ("F_commute", "F. Commute constraints and distance logic", "recommend_structured",
     "Give me options between 20 and 40 minutes from Boston."),
    ("F_commute", "F. Commute constraints and distance logic", "recommend_structured",
     "Find towns under 30 minutes and under 800k."),
    ("F_commute", "F. Commute constraints and distance logic", "recommend_structured",
     "Find safe towns within 45 minutes but not over 900k."),
    ("F_commute", "F. Commute constraints and distance logic", "recommend_structured",
     "I don't care about commute at all; optimize schools and safety."),
    ("F_commute", "F. Commute constraints and distance logic", "recommend_structured",
     "I want the shortest commute possible under 700k."),
    ("F_commute", "F. Commute constraints and distance logic", "recommend_structured",
     "Find far-out towns with strong schools."),
    ("F_commute", "F. Commute constraints and distance logic", "recommend_structured",
     "Show me towns where commute is the main downside."),
    # G. Coastal, region, and geography filters
    ("G_coastal", "G. Coastal, region, and geography filters", "recommend_structured",
     "Find coastal suburbs under 900k with decent schools."),
    ("G_coastal", "G. Coastal, region, and geography filters", "recommend_structured",
     "Show me North Shore towns with good safety."),
    ("G_coastal", "G. Coastal, region, and geography filters", "recommend_structured",
     "Find South Shore towns under 800k."),
    ("G_coastal", "G. Coastal, region, and geography filters", "recommend_structured",
     "Give me coastal-only results, no inland towns."),
    ("G_coastal", "G. Coastal, region, and geography filters", "recommend_structured",
     "Find a coastal town with low crime and a reasonable commute."),
    ("G_coastal", "G. Coastal, region, and geography filters", "recommend_structured",
     "Which coastal towns are under 750k?"),
    ("G_coastal", "G. Coastal, region, and geography filters", "lookup_single_town",
     "Is Reading actually coastal?"),
    ("G_coastal", "G. Coastal, region, and geography filters", "lookup_single_town",
     "Is Boxford coastal or just North Shore/inland?"),
    ("G_coastal", "G. Coastal, region, and geography filters", "recommend_structured",
     "Find a North Shore town that is not too expensive."),
    ("G_coastal", "G. Coastal, region, and geography filters", "recommend_structured",
     "Find South Shore family towns with good schools."),
    ("G_coastal", "G. Coastal, region, and geography filters", "recommend_structured",
     "Find coastal towns where safety is not terrible."),
    ("G_coastal", "G. Coastal, region, and geography filters", "recommend_structured",
     "Find me something near the ocean but still somewhat affordable."),
    ("G_coastal", "G. Coastal, region, and geography filters", "recommend_structured",
     "Find towns with a beach/coastal feel under $1m."),
    ("G_coastal", "G. Coastal, region, and geography filters", "recommend_structured",
     "I want a coastal town, but not Boston or Revere."),
    ("G_coastal", "G. Coastal, region, and geography filters", "recommend_structured",
     "Find North Shore towns with lower home prices."),
    # H. Semantic / vibe prompts
    ("H_semantic", "H. Semantic / vibe prompts", "recommend_semantic",
     "I want somewhere quiet, educated, and family-focused."),
    ("H_semantic", "H. Semantic / vibe prompts", "recommend_semantic",
     "Find a suburb that feels like Acton but costs less."),
    ("H_semantic", "H. Semantic / vibe prompts", "recommend_semantic",
     "Give me towns similar to Wellesley but not as expensive."),
    ("H_semantic", "H. Semantic / vibe prompts", "recommend_semantic",
     "I like Cambridge's amenities but want safer and cheaper."),
    ("H_semantic", "H. Semantic / vibe prompts", "recommend_semantic",
     "Find something with a classic New England town feel."),
    ("H_semantic", "H. Semantic / vibe prompts", "recommend_semantic",
     "I want a town with a village-center vibe and good schools."),
    ("H_semantic", "H. Semantic / vibe prompts", "recommend_semantic",
     "Give me a less intense version of Brookline."),
    ("H_semantic", "H. Semantic / vibe prompts", "recommend_semantic",
     "Find me a suburb like Lexington but with a lower price."),
    ("H_semantic", "H. Semantic / vibe prompts", "recommend_semantic",
     "I want a peaceful town with strong family appeal."),
    ("H_semantic", "H. Semantic / vibe prompts", "recommend_semantic",
     "Find a not-too-urban suburb with strong schools and safety."),
    ("H_semantic", "H. Semantic / vibe prompts", "recommend_semantic",
     "I want a coastal vibe without paying Marblehead prices."),
    ("H_semantic", "H. Semantic / vibe prompts", "recommend_semantic",
     "Find towns like Sharon but closer to Boston."),
    ("H_semantic", "H. Semantic / vibe prompts", "recommend_semantic",
     "Find towns like Burlington but with better safety."),
    ("H_semantic", "H. Semantic / vibe prompts", "recommend_semantic",
     "I want a balanced suburb, not elite-expensive but not sketchy."),
    ("H_semantic", "H. Semantic / vibe prompts", "recommend_semantic",
     "Find a quiet town with good schools where commute is the tradeoff."),
    # I. Inverted, unusual, and don't-care preferences
    ("I_inverted", "I. Inverted, unusual, and don't-care preferences", "recommend_structured",
     "Find cheaper towns even if schools are weak."),
    ("I_inverted", "I. Inverted, unusual, and don't-care preferences", "recommend_structured",
     "Show me affordable towns where crime is a downside."),
    ("I_inverted", "I. Inverted, unusual, and don't-care preferences", "recommend_structured",
     "I don't care about schools; optimize price and commute."),
    ("I_inverted", "I. Inverted, unusual, and don't-care preferences", "recommend_structured",
     "I don't care about safety; find cheap towns near Boston."),
    ("I_inverted", "I. Inverted, unusual, and don't-care preferences", "recommend_structured",
     "Find high-crime towns that are still affordable."),
    ("I_inverted", "I. Inverted, unusual, and don't-care preferences", "recommend_structured",
     "Show me risky but cheap towns, and explain the risks."),
    ("I_inverted", "I. Inverted, unusual, and don't-care preferences", "recommend_structured",
     "Find towns with low school scores but good commute."),
    ("I_inverted", "I. Inverted, unusual, and don't-care preferences", "recommend_structured",
     "I want the cheapest towns, even if they have tradeoffs."),
    ("I_inverted", "I. Inverted, unusual, and don't-care preferences", "recommend_structured",
     "Rank towns by worst safety among affordable places."),
    ("I_inverted", "I. Inverted, unusual, and don't-care preferences", "recommend_structured",
     "Find towns with bad safety but low prices."),
    ("I_inverted", "I. Inverted, unusual, and don't-care preferences", "recommend_structured",
     "I care only about affordability; ignore school and safety if needed."),
    ("I_inverted", "I. Inverted, unusual, and don't-care preferences", "recommend_structured",
     "Find towns where the main upside is price."),
    ("I_inverted", "I. Inverted, unusual, and don't-care preferences", "recommend_structured",
     "Find towns where schools are the weak point."),
    ("I_inverted", "I. Inverted, unusual, and don't-care preferences", "recommend_structured",
     "Find towns with high crime but short commute."),
    ("I_inverted", "I. Inverted, unusual, and don't-care preferences", "recommend_structured",
     "Show me lower-ranked towns that might still be worth considering."),
]

LABELS = {k: lbl for k, lbl, _, _ in CASES}


def main() -> None:
    cases = []
    counters: dict[str, int] = {}
    for cat, label, intent, prompt in CASES:
        counters[cat] = counters.get(cat, 0) + 1
        cases.append({
            "id": f"{cat}_{counters[cat]:02d}",
            "category": cat,
            "category_label": label,
            "expected_intent": intent,
            "prompt": prompt,
        })

    payload = {
        "description": "Phase 1.2 holdout suite — unseen prompts, harder than original 150",
        "prompt_count": len(cases),
        "cases": cases,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Wrote {len(cases)} cases to {OUT}")


if __name__ == "__main__":
    main()
